### ISSUE TITLE
Text editor link highlights are the same color for existant and non-existant links

### ISSUE THREAD

**Issue by tekwizz123** [TriDiamond/Obsidian-Obsidianite#30]
Title pretty much says it all. In the preview pane, the color for existant and non-existant links are different, as non-existant links show up in a faded grey, whilst existing links have a blue underline if an internal link, or purple underline if external. Yet in editor mode, the same link shows with a blue underline regardless of if the linked note exists or not.

**Comment by TriDiamond** [comment]
Ok, I will work on it this week. :)

**Comment by krokofant** [comment]
It seems that Obsidian itself does not differentiate between existing and non-existing links in editing mode. So the editing mode can't be fixed here.
![image](https://user-images.githubusercontent.com/5908498/194766956-15ccf393-9043-4b34-b352-3e3a08100f8d.png)

![image](https://user-images.githubusercontent.com/5908498/194766943-132d5c49-b3f6-49f5-b1ca-f63693404e07.png)

Unfortunately this problem also exists for the live preview mode, and it's actually a little worse there.
![image](https://user-images.githubusercontent.com/5908498/194767153-48c2e912-8a26-4175-9842-dd4c9c57b02a.png)

**Comment by bennyxguo** [comment]
@krokofant I got this one fixed by applying the underline style to the `cm-underline` class inside the cm-link. Thanks for keeping me updated on these issues and doing the contributions! 👍🏻

**Comment by krokofant** [comment]
@bennyxguo That's great! You fixed the live preview issue (which was reported separately), but this issue I assume still exists.
That existing and non-existing link references all look the same in edit mode & live preview mode. As far as I can tell Obsidian only exposes classes for targeting _existing links_ in read mode (`.internal-link.is-unresolved`).

Edit mode:
![image](https://user-images.githubusercontent.com/5908498/194784395-8a647ac7-f020-4490-a0d4-584dce9a8383.png)
```html
<div class="cm-line"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-link"><span class="cm-underline">This exists</span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
<div class="cm-line"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><span class="cm-link"><span class="cm-underline">This doesn't exist</span></span><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"><img class="cm-widgetBuffer" aria-hidden="true"><span contenteditable="false"></span><img class="cm-widgetBuffer" aria-hidden="true"></div>
```

Read mode:
![image](https://user-images.githubusercontent.com/5908498/194784407-34995b4b-9d85-485a-b0ee-b5bd2d1a1be2.png)
```html
<a class="internal-link" data-href="Test document" href="Test document" target="_blank" rel="noopener">This exists</a>
<br>
<a class="internal-link is-unresolved" data-href="Test2" href="Test2" target="_blank" rel="noopener">This doesn't exist</a>
```

I tried doing a quick search on the forum about this but didn't find anything.

**Comment by bennyxguo** [comment]
Thanks for the detail report, let me try it out.
